version: "3.8"
services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: qwerty
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: archive_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
