name: Deploy to Server

on:
  push:
    branches:
      - main   # или другая твоя основная ветка

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy files to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/qwerty_assistant
            echo ">>> Pulling latest code"
            git fetch --all
            git reset --hard origin/main

            echo ">>> Rebuilding Docker images"
            docker compose build --no-cache

            echo ">>> Restarting containers"
            docker compose down
            docker compose up -d

            echo ">>> Deployment finished!"